export const NYC_COLLEGES = [
  // CUNY
  "Baruch College",
  "Brooklyn College",
  "City College of New York (CCNY)",
  "College of Staten Island",
  "Hunter College",
  "John Jay College of Criminal Justice",
  "Lehman College",
  "Medgar Evers College",
  "New York City College of Technology (City Tech)",
  "Queens College",
  "York College",
  "CUNY Graduate Center",
  "CUNY School of Professional Studies",
  "Borough of Manhattan Community College (BMCC)",
  "Bronx Community College",
  "Guttman Community College",
  "Hostos Community College",
  "Kingsborough Community College",
  "LaGuardia Community College",
  "Queensborough Community College",
  // SUNY (NYC campuses)
  "SUNY Maritime College",
  "SUNY Downstate Health Sciences University",
  "SUNY College of Optometry",
  // Private
  "New York University (NYU)",
  "Columbia University",
  "Fordham University",
  "St. John's University",
  "Pace University",
  "The New School",
  "Yeshiva University",
  "Long Island University (LIU) Brooklyn",
  "Adelphi University",
  "Manhattan College",
  "Marymount Manhattan College",
  "Pratt Institute",
  "Parsons School of Design",
  "Cooper Union",
  "Barnard College",
  "Columbia University School of General Studies",
];